[package]
name = "reservoir-research"
version = "0.1.0"
authors = ["Emil Ohlsson <emil@kottland.net>"]
edition = "2018"

[dependencies]
regex = "1"
coding-challenge-utils = {path = "../../../coding-challenge-utils/"}
