[package]
name = "maze"
version = "0.1.0"
authors = ["Emil Ohlsson <kotte@kottland.net>"]

[dependencies]
coding-challenge-utils = { git = "https://github.com/EmilOhlsson/coding-challenge-utils.git" }
