[package]
name = "settlers-of-the-north-pole"
version = "0.1.0"
authors = ["Emil Ohlsson <emil@kottland.net>"]
edition = "2018"

[dependencies]
coding-challenge-utils = {path = "/home/kotte/workspace/coding-challenge-utils" }
