[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = 'Advent of Code'
version = '0.1.0'
description = 'My solutions for advent of code'
readme = 'README.md'
requires-python = '3.13'
