[package]
name = "chronical-coordinates"
version = "0.1.0"
authors = ["Emil Ohlsson <emil@kottland.net>"]
edition = "2018"

[dependencies]
coding-challenge-utils = {git = 'https://github.com/EmilOhlsson/coding-challenge-utils'}

